[package]
name = "shrimp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
game-loop = "0.10.2"
nalgebra = "0.32.3"
pixels = "0.13.0"
rayon = "1.7.0"
winit = "0.28.6"



