[package]
name = "teapot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
game-loop = {version = "0.10.2", features = ["winit"] }
shrimp = { path = "../.."}
winit = "0.28.6"
